name: Build app

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_server:
    name: Fileshare-server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@main
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3


      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-artifact
          retention-days: 1
          path: |
            ./migrations/*
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}

  build_web_app:
    name: Fileshare-webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - working-directory: ./web_client
        run: npm install
      - working-directory: ./web_client
        run: npm run prod
      - uses: actions/upload-artifact@main
        with:
          name: webapp-artifact
          retention-days: 1
          path: ./web_client/public/*

  package:
    name: package app
    runs-on: ubuntu-latest
    needs: [build_server, build_web_app]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Retrieve server data
        uses: actions/download-artifact@main
        with:
          name: server-artifact
          path: ./server_artifact

      - name: Retrieve webapp data
        uses: actions/download-artifact@main
        with:
          name: webapp-artifact
          path: ./web_client_artifact/public

      - run: mkdir fileshare
      - run: mkdir migration
      - run: unzip "./server_artifact/output/FileshareApi_null_x86_64-unknown-linux-musl.zip" -d ./fileshare
      - run: mv ./server_artifact/migrations/* ./fileshare
      - run: mv ./web_client_artifact/* ./fileshare


      - uses: actions/upload-artifact@main
        with:
          name: FileshareApp
          path: |
            ./fileshare
