name: Build app

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_server:
    name: Fileshare-server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@main
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3


      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-artifact
          retention-days: 1
          path: |
            ./migrations/*
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}

  build_web_app:
    name: Fileshare-webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - working-directory: ./web_client
        run: npm install
      - working-directory: ./web_client
        run: npm run prod
      - uses: actions/upload-artifact@main
        with:
          name: webapp-artifact
          retention-days: 1
          path: ./web_client/public/*

  package:
    name: package app
    runs-on: ubuntu-latest
    needs: [build_server, build_web_app]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Retrieve server data
        uses: actions/download-artifact@main
        with:
          name: server-artifact
          path: ./server_artifact

      - name: Retrieve webapp data
        uses: actions/download-artifact@main
        with:
          name: webapp-artifact
          path: ./web_client_artifact/public

      - run: mkdir fileshare
      - run: mkdir fileshare/migrations
      - run: unzip "./server_artifact/output/FileshareApi_null_x86_64-unknown-linux-musl.zip" -d ./fileshare
      - run: mv ./server_artifact/migrations/* ./fileshare/migrations
      - run: mv ./web_client_artifact/* ./fileshare
      - run: zip fileshare_linux.zip ./fileshare/*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./fileshare.zip
          asset_name: fileshare.zip
          asset_content_type: application/zip
