name: Cargo Build & Test

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_rust:
    name: Fileshare - server - debian
    runs-on: debian-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@main
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose

  build_web_app:
    name: Fileshare - web app - debian
    runs-on: debian-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@main
      - run: npm install
      - run: npm run prod