name: Build app

on:
  push:
    tags:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_server:
    name: Fileshare-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - run: cargo run --release

      - run: apt-get install tree

      - run: tree .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-artifact
          retention-days: 1
          path: |
            ./migrations/*
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}

  build_web_app:
    name: Fileshare-webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - working-directory: ./web_client
        run: npm install
      - working-directory: ./web_client
        run: npm run prod
      - uses: actions/upload-artifact@main
        with:
          name: webapp-artifact
          retention-days: 1
          path: ./web_client/public/*

  package:
    name: package app
    runs-on: ubuntu-latest
    needs: [build_server, build_web_app]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Retrieve server data
        uses: actions/download-artifact@main
        with:
          name: server-artifact
          path: ./server_artifact

      - name: Retrieve webapp data
        uses: actions/download-artifact@main
        with:
          name: webapp-artifact
          path: ./web_client_artifact/public

      - run: wget https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-linux-x64.tgz
      - run: tar zxvf pdfium-linux-x64.tgz

      - run: mkdir fileshare
      - run: mkdir fileshare/migrations
      - run: unzip "./server_artifact/output/FileshareApi_null_x86_64-unknown-linux-musl.zip" -d ./fileshare
      - run: mv ./lib/libpdfium.so ./fileshare/libpdfium.so
      - run: mv ./server_artifact/migrations/* ./fileshare/migrations
      - run: mv ./web_client_artifact/* ./fileshare
      - run: zip -r fileshare_linux.zip ./fileshare/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: fileshare_linux.zip
